language: haskell

ghc:
- 7.8

addons:
  apt:
    packages:
    - libgtk-3-dev

install:
- cabal install alex happy
- cabal install gtk2hs-buildtools
- cabal install --only-dependencies --enable-tests

script:
- cabal configure --enable-tests
- cabal build --ghc-options="-Werror"
- cabal test
- cabal check
